workers: 10
save_graph_animation: false
graph_animation_duration_per_step: 0.1

prompt_tmpl_path: configs/prompts.toml
service_llm_provider: openai
service_llm_model: gpt-4o-mini
service_llm_gen_config_path: configs/gpt_gen_configs.yaml

save_raw_graph: false
save_nla_graph: true
